[package]
name = "aether"
version = "1.0.0"
edition = "2024"
description = "A daemon-based terminal music player"
[dependencies]
clap = { version = "4.6.1", features = ["derive"] }
ctrlc = "3.5.2"
dirs = "6.0.0"
lofty = "0.24.0"
rodio = "0.22.2"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
walkdir = "2.5.0"
rusqlite = { version = "0.40.1", features = ["bundled"] }
rand = "0.10.2"
zbus = "5.18"
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros", "time"] }
zvariant = "5.13.1"
sha2 = "0.11.0"
hex = "0.4.3"
libc = "0.2.189"
tempfile = "3.27.0"
reqwest = {version = "0.13.4", features = ["blocking", "json"]}
flate2 = "1.1.9"
tar = "0.4.46"
semver = "1.0.28"
