name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: x86_64
            runner: ubuntu-22.04
            artifact: aether-linux-x86_64

          - arch: aarch64
            runner: ubuntu-22.04-arm
            artifact: aether-linux-aarch64

    name: Build (${{ matrix.arch }})
    runs-on: ${{ matrix.runner }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            pkg-config \
            libasound2-dev

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo
        uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build --release

      - name: Prepare Release
        run: |
          mkdir -p ${{ matrix.artifact }}/assets/linux

          cp target/release/aether \
             ${{ matrix.artifact }}/

          cp target/release/aetherd \
             ${{ matrix.artifact }}/

          cp target/release/aether-setup \
             ${{ matrix.artifact }}/

          cp assets/linux/aetherd.service \
             ${{ matrix.artifact }}/assets/linux/

      - name: Create Archive
        run: |
          tar -czf ${{ matrix.artifact }}.tar.gz \
              ${{ matrix.artifact }}

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ matrix.artifact }}.tar.gz
